### PR TITLE
Reversions on master

### PR DESCRIPTION
**Pull request by ulmus-scott**
@bennettpeter Rebased https://github.com/MythTV/FFmpeg/pull/1 onto mythtv/master

No conflicts.

### CODE REVIEW

**Comment by bennettpeter** [comment]
This has been merged into master

**Comment by ulmus-scott** [comment]
> This has been merged into master

@bennettpeter Did you forget to push?

Also, two new commits.

**Comment by bennettpeter** [comment]
> 



> Did you forget to push?

Yes - sorry - just pushed, but not the two new commits yet.

**Comment by bennettpeter** [comment]
I have merged two new commits into MythTV/FFmpeg/master

**Pull request merged**
